### ISSUE TITLE
different values for ACC metric

### ISSUE THREAD

**Issue by joenio** [analizo/analizo#179]
* sometimes ACC metric for Dog module is calculated as 7
* sometimes ACC metric for Dog module is calculated as 8

It must be tested to understand exactly what is going on.

```sh
./bin/analizo metrics t/samples/deep_inheritance/java/ | grep -A 1 -P "_module: Dog$"
_module: Dog
acc: 7
```

**Comment by LeaoLuciano** [comment]
This problem is caused by a Doxygen regression that appeared in release 1.9.4, introduced in this commit [https://github.com/doxygen/doxygen/commit/2976b67adcd1e2d3a787533566d93915ea237065]( https://github.com/doxygen/doxygen/commit/2976b67adcd1e2d3a787533566d93915ea237065).

Since that commit, it appears that Doxygen doesn't recognize constructor calls neither writing attributes of external classes.

```java
  public void sellDogTo(Human owner){
        Dog dog = new Dog();
        dog.name = "Toby";
        dog.owner = owner;

        owner.pet = dog;
    }
```

Result before the regression :
```dot
  /* list of edges */
  "Dog::getOwner()" -> "Dog::owner" [style = "dashed"];
  "Human::getPetName()" -> "Dog::name" [style = "dashed"];
  "Human::getPetName()" -> "Human::pet" [style = "dashed"];
  "ShopController::main()" -> "Human::name" [style = "dashed"];
  "ShopController::main()" -> "VenderShop::sellDogTo(Human)" [style = "solid"];
  "VenderShop::sellDogTo(Human)" -> "Dog::name" [style = "dashed"];
  "VenderShop::sellDogTo(Human)" -> "Dog::owner" [style = "dashed"];
  "VenderShop::sellDogTo(Human)" -> "Human::pet" [style = "dashed"];
```

Result after the regression:
```dot
/* list of edges */
  "Dog::getOwner()" -> "Dog::owner" [style = "dashed"];
  "Human::getPetName()" -> "Dog::name" [style = "dashed"];
  "Human::getPetName()" -> "Human::pet" [style = "dashed"];
  "ShopController::main()" -> "VenderShop::sellDogTo(Human)" [style = "solid"];
```

So some method calls are missed in Afferent Connections metric calculation.

**Comment by joenio** [comment]
thanks @LeaoLuciano for your time investigating this issue

then this is a issue that could be fixed on doxygen side, it would be good to fire a new gub on doxygen repository to document it

**Comment by joenio** [comment]
analizo build is failing on debian sid as we can see in this report by debci https://ci.debian.net/data/autopkgtest/unstable/amd64/a/analizo/37463431/log.gz

below copy/paste of the lines with the failing test:
```
128s # Scenario "Animals" project
128s ok 803 - Given I am in t/samples/animals/csharp
128s # 
128s ok 804 - When I run "analizo metrics ."
128s # 
128s not ok 805 - Then analizo must report that the project has total_abstract_classes = 1
128s 
128s # Failed test 'Then analizo must report that the project has total_abstract_classes = 1'
128s # at t/features/metrics/abstract_classes.feature line 19.
128s # 
128s #   in step at t/features/metrics/abstract_classes.feature line 19.
128s #     not ok
128s #     #   Failed test at /tmp/autopkgtest-lxc.bzr7o03w/downtmp/autopkgtest_tmp/smokelRo5AP/t/features/step_definitions/analizo_steps.pl line 143.
128s #     #          got: 2
128s #     #     expected: 1
128s #     ok 3 - Step ran to completion
128s #     1..2
128s #     # Looks like you failed 1 test of 2.
128s # Scenario "Polygons" project
128s ok 806 - Given I am in t/samples/polygons/cpp
128s # 
```

I didnt check if it is in fact related to his issue but looks related to the same problem on ACC we see here in this issue

**Comment by lucadiogo** [comment]
I ran git bisect between doxygen 1.9.3, which passes all Analizo tests and the [current commit] (https://github.com/doxygen/doxygen/commit/e0b3a8923baf7ff76a018a5fea66eef23794fbf0), which fails both errors mentioned here, and found that the commit which introduced the abstract classes error was commit [2acf938](https://github.com/doxygen/doxygen/commit/2acf938e681970f70aa6e81dc89d6ca9fe8c33d8). This commit happened between versions 1.9.7 and 1.9.8, after the one which introduced the ACC error.

**Comment by LeaoLuciano** [comment]
> then this is a issue that could be fixed on doxygen side, it would be good to fire a new gub on doxygen repository to document it

Reported here: https://github.com/doxygen/doxygen/issues/10281

**Comment by emollier** [comment]
Hi,

About the abstract classes error affecting the csharp test, it went eventually documented as [Debian bug 1051534], and if I trust the message in commit 6cdd646d723106bddc4f9f01cbbbf9370e347925, the new behavior with two abstract classes detected instead of one seems to be the correct one.

It may not be directly related to the present analizo issue, but I thought you might want to be aware of it.

Have a nice day,  :)
Étienne.

[Debian bug 1051534]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1051534

**Comment by joenio** [comment]
Thanks @emollier <3

closing this issue.
