### ISSUE TITLE
Do not show unsupported Metrics

### ISSUE THREAD

**Issue by carlosfilipe** [analizo/analizo#60]
Analizo shows 0 for the metrics that are not calculated. Would be great if with a flag, like verbose, appeared a message such as "not supported" or the metric do not appears in the output.

**Comment by joenio** [comment]
why supress metrics with 0  from the output? zero have no meaning for most of source code metrics.

**Comment by joenio** [comment]
I suppose this issue has no any real application, closing.

**Comment by rafamanzo** [comment]
Sorry for getting here late! I have one use case where 0 breaks things and "not existent" would be useful: when you are aggregating the results (for example Mezuro's Kalibro does that).

When you choose to aggregate using the median for example:

* 0,0,1,2,3 will result in 1
* 1,2,3 will result in 2

Now comes the question I don't know the answer right now (and you might know): is there a metric where 0 is different than "not existent"?

If there is no such metric, it is ok to keep 0 and anyone aggregating can just remove 0s. Just a documentation about this project decision would be enough.

If there is such metric, then I think the request may be valid.

**Comment by joenio** [comment]
I've reading some chapters of the book "Software Metrics: A Rigorous and Practical Approach, Third Edition"[1] looking for a formal definition about meaning of zero for software product metrics and despite missing a explicit definition about that I found that for some metrics "null value" and zero has the same meaning.

I copy below some parts of the book about that:

(book page 336) 8.1 PROPERTIES OF SOFTWARE SIZE
1. Nonnegativity: All systems have nonnegative size.
2. Null value: The size of a system with no elements is zero.
3. Additivity: The size of the union of two modules is the sum of sizes of the two modules after subtracting the size of the intersection.

(book page 373) 9.1.1 Structural Complexity Properties
1. Nonnegativity: System complexity cannot be negative.
2. Null value: The complexity of a system with no links is zero.
3. Symmetry: The complexity of a system does not depend on how links are represented.
4. Module monotonicity: System complexity “is no less than the sum of the complexities of any two of its modules with no relationships in common.”
5. Disjoint module additivity: The complexity of a system of disjoint modules is the sum of the complexities of the modules.

(book page 373) 9.1.2 Length Properties
1. Nonnegativity: System length cannot be negative.
2. Null value: A system with no links has zero length.
3. Nonincreasing monotonicity for connected components: Length does not increase when adding links between connected elements.
4. Nondecreasing monotonicity for nonconnected components: Length does not decrease when adding links between nonconnected elements.
5. Disjoint modules: The length of a system of disjoint modules is equal to the length of the module with the greatest length.

(book page 374) 9.1.3 Coupling Properties
1. Nonnegativity: Module coupling cannot be negative.
2. Null value: A module without links to elements that are external to the module has zero coupling.
3. Monotonicity: Adding intermodule relationships does not decrease
coupling.
4. Merging modules: Merging two modules creates a new module that has coupling that is at most the sum of the coupling of the two modules.
5. Disjoint module additivity: Merging disjoint modules without links between them creates a new module with coupling that is the sum of the coupling of the original modules.

(book page 375) 9.1.4 Cohesion Properties
1. Nonnegativity and normalization: Module cohesion is normalized so that it is between zero and one.
2. Null value: A module whose elements have no links between them has zero cohesion.
3. Monotonicity: Adding links between elements in a module cannot decrease the cohesion of the module.
4. Merging modules: Merging two unrelated modules creates a new module with a maximum cohesion no greater than that of the original module with the greatest cohesion.

I don't know if I understood well what I read, maybe I understood wrong, but to me seens that 0 (zero) and null values have the same meaning in these cases.

I usually discard any metric with zero value when using analizo, I consider zero with no meaning even without a formal definition about that for all the metrics.

I'm going to document this as a project decision as you proposed, what do you think?

* [1] N. Fenton and J. Bieman, [Software Metrics: A Rigorous and Practical Approach](https://www.crcpress.com/Software-Metrics-A-Rigorous-and-Practical-Approach-Third-Edition/Fenton-Bieman/p/book/9781439838228), Third Edition, 3 edition. Boca Raton: CRC Press, 2014.

**Comment by rafamanzo** [comment]
Very nice! Agreed and thanks for the research.
