### ISSUE TITLE
Warning in analizo call

### ISSUE THREAD

**Issue by lucaskanashiro** [analizo/analizo#65]
In any analizo call:

Argument "2.49_01" isn't numeric in numeric ge (>=) at (eval 23) line 1.

**Comment by Ziul** [comment]
The error appears in the Debian [repository](https://packages.debian.org/search?keywords=libgraph-writer-dsm-perl) (Jessie and Sid) because they already updated the **libgraph-writer-dsm-perl** from 0.005-1 to 0.006-1. On Ubuntu the warning don't appears because they still with 0.005-1 in they [repository](https://launchpad.net/ubuntu/saucy/amd64/libgraph-writer-dsm-perl/0.005-1).

**Comment by joenio** [comment]
It's a bug on the module [Graph](http://metacpan.org/pod/Graph) related on [RT#107394](http://rt.cpan.org/Public/Bug/Display.html?id=107394) (solved) and already fixed on Debian [#782676](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=782676).
