### ISSUE TITLE
librelist.com mailing is offline

### ISSUE THREAD

**Issue by joenio** [analizo/analizo#84]
[2016-08-24] I've tried send message to list analizo@librelist.com without success.

[2016-08-24] Then I tried contacting the Librelist's author on help@librelist.com, no answer.

We need another provider for mailing list of the Analizo project.

@terceiro @athos-ribeiro @lucaskanashiro @rafamanzo do you suggest any good alternative to Librelist.com?

**Comment by athos-ribeiro** [comment]
We are having the same issues with Mezuro[1].

Sourceforge provides a maling list feature. Alioth (Debian) also provides mailing lists, but it would be nice to hear Kanashiro and Terceiro's thoughts on that. With either sourceforge or alioth we'd want to consider maintaining a mirror (or maybe even migrate the project) there since they are both forges. There's also GNU Savannah which provides mailing lists.

I do not know of any standalone mailing list service.

[1] mezuro.org

**Comment by joenio** [comment]
Thanks Athos! There is the Launchpad.net too. Which one do you think is the best choice?

* Sourceforge
* Alioth
* Savannah
* Launchpad

**Comment by athos-ribeiro** [comment]
Sorry for the delay. We could go for sourceforge and distribute tarballs with each analizo version there, how about that?

**Comment by terceiro** [comment]
you can already distribute tarballs on github. if the missing bit is just a maliing list we can use one at listas.softwarelivre.org; or even at google groups, really; it's not like we are avoiding proprietary infrastructure since everything else is already on github.

**Comment by lucaskanashiro** [comment]
Since the mailing list was created in google groups this issue was closed.
